name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

#  go:
#    runs-on: ubuntu-latest
#    steps:
#    - name: checkout hello-release
#      uses: actions/checkout@v2
#
#    - name: set up go
#      uses: actions/setup-go@v3
#
#    - name: build and test
#      working-directory: src
#      run: |
#        go build -v ./cmd/hello-server
#        go test -v ./...

  bosh:
    runs-on: ubuntu-latest
    steps:
      - name: checkout hello-release
        uses: actions/checkout@v2
      - name: create release
        uses: ./.github/actions/create-release
        with:
          tarball: hello-release.tgz
          version: '0.1.0'
          timestamp_version: true