name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  go_test:
    name: "Run Source Code Unit Tests"
    runs-on: ubuntu-latest
    steps:
    - name: checkout hello-release
      uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v3
      with:
        go-version-file: ./src/go.mod

    - name: test
      working-directory: src
      run: |
        go test -v ./...

    - name: build
      working-directory: src
      run: |
        go build -v ./cmd/hello-server
