---
name: Release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']

jobs:
  go_test:
    name: "Run Source Code Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: checkout hello-release
        uses: actions/checkout@v2

      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: test
        working-directory: src
        run: |
          go test -v ./...

      - name: build
        working-directory: src
        run: |
          go build -v ./cmd/hello-server

  bosh_release:
    name: "Create BOSH Release"
    needs: [ go_test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Hello Release
        uses: actions/checkout@v2
        with:
          set-safe-directory: 'true'

      - name: Configure git
        run: |
          git config --global user.name "Christopher Hunter"
          git config --global user.email "8398225+crhntr@users.noreply.github.com"
          git checkout -b create-release

      - name: Parse Tag Name
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Create BOSH Release
        uses: ./.github/actions/create-release
        env:
          CONFIG_PRIVATE_JSON_KEY: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          tarball: hello-release-${{ steps.vars.outputs.tag }}.tgz
          version: ${{ steps.vars.outputs.tag }}
          final: true

      - name: Commit Result
        env:
          BOSH_RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          set -euo pipefail
          
          git commit -am "Create Release ${BOSH_RELEASE_VERSION}"
          git fetch origin main
          git checkout main
          git pull -r origin main
          git checkout -
          git rebase main
          git push origin main

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: hello-release-${{ steps.vars.outputs.tag }}.tgz
