---
name: Release

on:
  push:
    tags: ['build/v[0-9]+.[0-9]+.[0-9]+*']

jobs:
  go_test:
    name: "Run Source Code Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: checkout hello-release
        uses: actions/checkout@v2

      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: test
        working-directory: src
        run: |
          go test -v ./...

      - name: build
        working-directory: src
        run: |
          go build -v ./cmd/hello-server

  bosh_release:
    name: "Create BOSH Release"
    needs: [ go_test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Hello Release
        uses: actions/checkout@v2
        with:
          set-safe-directory: 'true'

      - name: Parse Tag Name
        id: vars
        run: echo "tag-version=${GITHUB_REF#refs/*/build/v}" >> $GITHUB_OUTPUT

      - name: Create BOSH Release
        uses: ./.github/actions/create-release
        id: create-release
        env:
          CONFIG_PRIVATE_JSON_KEY: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GIT_USER_NAME: "Christopher Hunter"
          GIT_USER_EMAIL: "8398225+crhntr@users.noreply.github.com"
        with:
          tarball: hello-release-${{ steps.vars.outputs.tag-version }}.tgz
          version: ${{ steps.vars.outputs.tag-version }}
          final: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: hello-release-*.tgz
          tag_name: ${{ steps.vars.outputs.tag-version }}
          prerelease: ${{ steps.create-release.outputs.pre-release-version }}
